// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zAddress = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    line1: z.string().nullable(),
    line2: z.string().nullish(),
    city: z.string().nullable(),
    state: z.string().nullable(),
    postalCode: z.string().nullable(),
    country: z.string().nullable(),
    contactId: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional()
});

export const zAuthResponse = z.object({
    id: z.string().nullish(),
    email: z.string().nullish(),
    roles: z.array(z.string()).nullish(),
    token: z.string().nullish(),
    expiresAt: z.iso.datetime().optional()
});

export const zContact = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    firstName: z.string().nullable(),
    lastName: z.string().nullable(),
    email: z.string().nullable(),
    dateOfBirth: z.iso.date().nullish(),
    isFavorite: z.boolean()
});

export const zBirthdayGroup = z.object({
    month: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    contacts: z.array(zContact).nullish()
});

export const zLoginRequest = z.object({
    email: z.string().nullish(),
    password: z.string().nullish()
});

export const zPhoneNumber = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    number: z.string().nullable(),
    type: z.string().nullish(),
    contactId: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional()
});

export const zContactWithFullName = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    firstName: z.string().nullable(),
    lastName: z.string().nullable(),
    email: z.string().nullable(),
    dateOfBirth: z.iso.date().nullish(),
    isFavorite: z.boolean(),
    fullName: z.string().nullish(),
    primaryAddressId: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    primaryPhoneNumberId: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    addresses: z.array(zAddress).nullish(),
    phoneNumbers: z.array(zPhoneNumber).nullish()
});

export const zRegisterRequest = z.object({
    firstName: z.string().nullish(),
    lastName: z.string().nullish(),
    email: z.string().nullish(),
    password: z.string().nullish()
});

export const zUpdateFavoriteDto = z.object({
    isFavorite: z.boolean()
});

export const zPostApiAuthRegisterBody = zRegisterRequest;

export const zPostApiAuthLoginBody = zLoginRequest;

/**
 * OK
 */
export const zPostApiAuthLoginResponse = zAuthResponse;

/**
 * OK
 */
export const zGetApiContactsResponse = z.array(zContact);

export const zPostApiContactsBody = zContact;

/**
 * OK
 */
export const zPostApiContactsResponse = zContact;

export const zDeleteApiContactsByIdPath = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
});

export const zGetApiContactsByIdPath = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
});

/**
 * OK
 */
export const zGetApiContactsByIdResponse = zContactWithFullName;

export const zPutApiContactsByIdBody = zContact;

export const zPutApiContactsByIdPath = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
});

/**
 * OK
 */
export const zGetApiContactsBirthdaysResponse = z.array(zBirthdayGroup);

/**
 * OK
 */
export const zGetApiContactsFavoritesResponse = z.array(zContact);

export const zPatchApiContactsByIdFavoriteBody = zUpdateFavoriteDto;

export const zPatchApiContactsByIdFavoritePath = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
});
